csr1:
    groups:
        - iosxe_routers
    hostname: 192.168.1.1
    data:
        site: beijing
        type: router
        router_id: 1.1.1.1
        ospf_process_id: 1
        interface_list:
            -   interface_name: Loopback0
                ipaddr: 1.1.1.1
                netmask: 255.255.255.255
            -   interface_name: GigabitEthernet1
                ipaddr: 137.78.5.254
                netmask: 255.255.255.0
            -   interface_name: GigabitEthernet2
                ipaddr: 61.128.1.254
                netmask: 255.255.255.0
        ospf_network_list:
            -   network: 137.78.5.0
                wildmask: 0.0.0.255
                area: 0
            -   network: 61.128.1.0
                wildmask: 0.0.0.255
                area: 0

csr2:
#    groups:
#        - iosxe_routers
    hostname: 192.168.1.2
    data:
        site: shanghai
        type: router
        router_id: 2.2.2.2
        ospf_process_id: 1
        interface_list:
            -   interface_name: Loopback0
                ipaddr: 2.2.2.2
                netmask: 255.255.255.255
            -   interface_name: GigabitEthernet1
                ipaddr: 61.128.1.1
                netmask: 255.255.255.0
            -   interface_name: GigabitEthernet2
                ipaddr: 202.100.1.1
                netmask: 255.255.255.0
        ospf_network_list:
            -   network: 61.128.1.0
                wildmask: 0.0.0.255
                area: 0
            -   network: 202.100.1.0
                wildmask: 0.0.0.255
                area: 0

asa1:
    groups:
        - asas
    hostname: 192.168.1.3
    data:
        site: beijing
        type: firewall
        interface_list:
            -   interface_name: GigabitEthernet0/0
                ipaddr: 202.100.1.254
                netmask: 255.255.255.0
                nameif: Outside
                security_lvl: 0
            -   interface_name: GigabitEthernet0/1
                ipaddr: 10.1.1.254
                netmask: 255.255.255.0
                nameif: Inside
                security_lvl: 100